# Tables

## demogTabCont
        

```{r results='asis',echo=FALSE}
 fn.src('demogTabCont','TFL',hlp.dir)
 ```
        

```{r demogTabCont, echo=TRUE, results='asis'}
                 
        

### Name: demogTabCont
### Title: Demographics table for continuous variables
### Aliases: demogTabCont

### ** Examples

 require(texPreview)
 Knit<-!is.null(knitr::opts_knit$get('rmarkdown.pandoc.to')) #Check if in knit environment
 Chk<-interactive()||Knit #Check for Rstudio and knit environment

data("twoCmt")

if(!Knit) 
demogTabCont(twoCmt)

#Show Table in Viewer
if(Chk)  texPreview(obj = demogTabCont(twoCmt),
                    stem = paste0('demogTabContEx1'),
                    fileDir = fd,
                    imgFormat = 'svg',
                    returnType=rt,
                    ignore.stdout=T)
                    



        


    ```
    
## demogTabCat
        

```{r results='asis',echo=FALSE}
 fn.src('demogTabCat','TFL',hlp.dir)
 ```
        

```{r demogTabCat, echo=TRUE, results='asis'}
                 
        

### Name: demogTabCat
### Title: Demographics table for categorical variables
### Aliases: demogTabCat

### ** Examples

 require(texPreview)
 Knit<-!is.null(knitr::opts_knit$get('rmarkdown.pandoc.to')) #Check if in knit environment
 Chk<-interactive()||Knit #Check for Rstudio and knit environment

data("twoCmt")

if(!Knit) 

demogTabCat(twoCmt)

#Show Table in Viewer
if(Chk) texPreview(obj = demogTabCat(twoCmt),
                   stem = paste0('demogTabCatEx1'),
                   fileDir = fd,
                   imgFormat = 'svg',
                   returnType=rt,
                   ignore.stdout=T)
 
if(!Knit) 

demogTabCat(twoCmt,stratBy = '')

#Show Table in Viewer
if(Chk) texPreview(obj = demogTabCat(twoCmt,stratBy = ''),stem = paste0('demogTabCatEx2'),fileDir = fd,imgFormat = 'svg',returnType=rt,ignore.stdout=T)




        


    ```
    
## datacountTab
        

```{r results='asis',echo=FALSE}
 fn.src('datacountTab','TFL',hlp.dir)
 ```
        

```{r datacountTab, echo=TRUE, results='asis'}
                 
        

### Name: datacountTab
### Title: datacountTab
### Aliases: datacountTab

### ** Examples

 require(texPreview)
 Knit<-!is.null(knitr::opts_knit$get('rmarkdown.pandoc.to')) #Check if in knit environment
 Chk<-interactive()||Knit #Check for Rstudio and knit environment

 datFile=twoCmt%>%mutate(BLQ=(DV<=100&DV>0))
 datFile$rndGroup=sample(1:5,size = nrow(datFile),replace = T)
 datFile$NODOSE=datFile$DV==0
 out=datacountTab(datFile,
         groupBy = list(c("STUDY","Study Phase"),c('rndGroup','Randomization Group')),
         exclVar=list(BLQ=list(label='BLQ',flag=T),NODOSE=list(label='No Dose',flag=T))
 )
 
if(!Knit) 

out

#Show Table in Viewer
if(Chk)  texPreview(obj = out,
                    stem = paste0('datacountTabEx1'),
                    fileDir = fd,
                    imgFormat = 'svg',
                    returnType=rt,
                    ignore.stdout=T)




        


    ```
    
## RNM
        

```{r results='asis',echo=FALSE}
 fn.src('RNM','TFL',hlp.dir)
 ```
        

```{r RNM, echo=TRUE, results='asis'}
                 
        

### Name: RNM
### Title: Create a Nonmem run output table from the XML output
### Aliases: RNM

### ** Examples

 require(texPreview)
 Knit<-!is.null(knitr::opts_knit$get('rmarkdown.pandoc.to')) #Check if in knit environment
 Chk<-interactive()||Knit #Check for Rstudio and knit environment

if(!Knit) 

RNM(Run = '0069',proj=system.file('external',package = 'TFL'))

#Show Table in Viewer
if(Chk) texPreview(obj = RNM(Run = '0069',proj=system.file('external',package = 'TFL')),
                   stem = paste0('RNMEx1'),
                   fileDir = fd,imgFormat = 'svg',
                   returnType=rt,
                   ignore.stdout=T)




        


    ```
    
