# Figures

## ConcvTime
        

```{r results='asis',echo=FALSE}
fn.src('ConcvTime','TFL',hlp.dir)
```
        

```{r ConcvTime, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: ConcvTime
### Title: Concentration vs time profiles for individuals
### Aliases: ConcvTime

### ** Examples

data("twoCmt")
ConcvTime(datFile = twoCmt,ID = '1',ipredVar = 'IPRED')
ConcvTime(datFile = twoCmt,ID = '1',ipredVar = 'IPRED',minorTicks = T)



        

lapply(list.files(fig.dir,pattern = 'ConcvTime-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## ConcvTimeInd
        

```{r results='asis',echo=FALSE}
fn.src('ConcvTimeInd','TFL',hlp.dir)
```
        

```{r ConcvTimeInd, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: ConcvTimeInd
### Title: Concentration vs time profiles for groups of patients (spaghetti
###   plot)
### Aliases: ConcvTimeInd

### ** Examples

data("twoCmt")
twoCmt=twoCmt%>%mutate(DOSE=factor(DOSE))
ConcvTimeInd(datFile = twoCmt)
ConcvTimeInd(datFile = twoCmt,facetBy = 'SEX')



        

lapply(list.files(fig.dir,pattern = 'ConcvTimeInd-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## ConcvTimeMult
        

```{r results='asis',echo=FALSE}
fn.src('ConcvTimeMult','TFL',hlp.dir)
```
        

```{r ConcvTimeMult, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: ConcvTimeMult
### Title: Multipanel concentration vs time profiles for individual
###   patients
### Aliases: ConcvTimeMult

### ** Examples

data("twoCmt")
twoCmt=twoCmt%>%mutate(DOSE=factor(DOSE))
ConcvTimeMult(datFile = twoCmt,ipredVar='IPRED',genAll=F,page=1)
ConcvTimeMult(datFile = twoCmt,ipredVar='IPRED',genAll=F,page=2,nrow =5,ncol=4)



        

lapply(list.files(fig.dir,pattern = 'ConcvTimeMult-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## ConcvTimeSum
        

```{r results='asis',echo=FALSE}
fn.src('ConcvTimeSum','TFL',hlp.dir)
```
        

```{r ConcvTimeSum, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: ConcvTimeSum
### Title: Concentration vs time profiles for groups of patients (summary
###   plot)
### Aliases: ConcvTimeSum

### ** Examples

data("twoCmt")
twoCmt=twoCmt%>%mutate_each(funs(factor),DOSE,SEX)
ConcvTimeSum(datFile = manipDat(twoCmt,groupBy = 'SEX',sumThis = T))



        

lapply(list.files(fig.dir,pattern = 'ConcvTimeSum-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## GOF
        

```{r results='asis',echo=FALSE}
fn.src('GOF','TFL',hlp.dir)
```
        

```{r GOF, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: GOF
### Title: Goodness of fit plots
### Aliases: GOF

### ** Examples

data("twoCmt")
GOF(twoCmt,cwresBy = 'IRES')



        

lapply(list.files(fig.dir,pattern = 'GOF-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## OBSvIPRED
        

```{r results='asis',echo=FALSE}
fn.src('OBSvIPRED','TFL',hlp.dir)
```
        

```{r OBSvIPRED, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: OBSvIPRED
### Title: Standard goodness of fit plots for observed versus predicted
###   values
### Aliases: OBSvIPRED

### ** Examples

data("twoCmt")
OBSvIPRED(twoCmt%>%filter(DV>0),xBy='IPRED')
OBSvIPRED(twoCmt,xBy='IPRED',xScale = 'identity',markBy = 'SEX')



        

lapply(list.files(fig.dir,pattern = 'OBSvIPRED-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## QQplot
        

```{r results='asis',echo=FALSE}
fn.src('QQplot','TFL',hlp.dir)
```
        

```{r QQplot, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: QQplot
### Title: Create a standard Quantile-Quantile plot
### Aliases: QQplot

### ** Examples

data("twoCmt")
QQplot(twoCmt)
QQplot(twoCmt,markBy = 'SEX')
QQplot(twoCmt,facetBy = 'DOSE')



        

lapply(list.files(fig.dir,pattern = 'QQplot-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## barchartMult
        

```{r results='asis',echo=FALSE}
fn.src('barchartMult','TFL',hlp.dir)
```
        

```{r barchartMult, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: barchartMult
### Title: Bar charts
### Aliases: barchartMult

### ** Examples

data("twoCmt")
barchartMult(datFile = twoCmt)
barchartMult(datFile = twoCmt,catList = list(c('SEX','Gender')))
barchartMult(datFile = twoCmt,nrow=2)



        

lapply(list.files(fig.dir,pattern = 'barchartMult-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## covCat
        

```{r results='asis',echo=FALSE}
fn.src('covCat','TFL',hlp.dir)
```
        

```{r covCat, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: covCat
### Title: Boxplots
### Aliases: covCat

### ** Examples

data("twoCmt")
covCat(twoCmt,catList = list('SEX'),conList = 'IPRED',nCols=1)
covCat(twoCmt,catList = list(list('SEX','Gender'),list('DOSE')),conList = list(list('IPRED'),list('ETA1',expression(eta[1]))))



        

lapply(list.files(fig.dir,pattern = 'covCat-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## covCon
        

```{r results='asis',echo=FALSE}
fn.src('covCon','TFL',hlp.dir)
```
        

```{r covCon, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: covCon
### Title: Scatterplots
### Aliases: covCon

### ** Examples

data("twoCmt")
covCon(twoCmt,conList_x = 'IPRED',conList_y = 'ETA1',nCol=1)
covCon(twoCmt,
conList_x = list(
list('IPRED','Individual Prediction'),
list('IRES','Individual Residual')
),
conList_y = list(
list('ETA1',expression(eta[1]))
)
)




        

lapply(list.files(fig.dir,pattern = 'covCon-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## distMult
        

```{r results='asis',echo=FALSE}
fn.src('distMult','TFL',hlp.dir)
```
        

```{r distMult, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: distMult
### Title: Multipanel distribution
### Aliases: distMult

### ** Examples

data("twoCmt")
distMult(twoCmt)
distMult(twoCmt,order = c("Boxplot","Density","QQ"))



        

lapply(list.files(fig.dir,pattern = 'distMult-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## ggpairs
        

```{r results='asis',echo=FALSE}
fn.src('ggpairs','TFL',hlp.dir)
```
        

```{r ggpairs, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: ggpairs
### Title: Correlation Comparison plot
### Aliases: ggpairs

### ** Examples

data("twoCmt")
ggpairs(twoCmt,xCols=c('ETA1','ETA2'))
ggpairs(twoCmt,xCols=c('ETA1','ETA2','ETA5'))



        

lapply(list.files(fig.dir,pattern = 'ggpairs-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

## paramDist
        

```{r results='asis',echo=FALSE}
fn.src('paramDist','TFL',hlp.dir)
```
        

```{r paramDist, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: paramDist
### Title: Parameter Distribution Plots
### Aliases: paramDist

### ** Examples

data("twoCmt")
paramDist(twoCmt)
paramDist(twoCmt,xCols=c('ETA1','ETA2'),xLab=c(expression(eta[1]),expression(eta[2])))



        

lapply(list.files(fig.dir,pattern = 'paramDist-',full.names = T),
           function(x) base64enc::dataURI(file = x, mime='image/png'))%>%
           loryR(images_per_page = 1, options = list(rewind=TRUE))
```

