gitDir <- getwd()

tabList=list(
    inputId=c("ConcvTimeNum",
              "ConcvTimeMultNum",
              "ConcvTimeGroupNum",
              #"demogTabNum",
              #"demog1TabNum",
              "OBSvPREDNum", 
              "paramDistNum", 
              "covCatNum", 
              "covConNum", 
              "corPairsNum", 
              "QQplotNum",
              #"DescParamStatNum", 
              "NMTabNum",
              "demogTabCatNum",
              "demogTabContNum",
              "GOFNum",
              "inputTableNum",
              "inputFigureNum",
              "inputListingNum",
              "inputListing_textNum",
              "subjectExclusionsTabNum",
              "observationExclusionsTabNum",
              "subjectExclusionsSummaryTabNum",
              "observationExclusionsSummaryTabNum",
              "distMultNum",
              "barchartMultNum"
              #, "DescListNum"
    ),
    label=c("Serum Concentration Versus Time-Individual",
            "Serum Concentration Versus Time-Multipanel",
            "Serum Concentration Versus Time-Groups",
            #"Basic Demographics", 
            #"Demographics Type 1",  
            "Observed Versus Predicted", 
            "Parameter Distribution",
            "Categorical Covariance",
            "Continuous Covariance",
            "Correlation Pairs",
            "Quantile Plot",
            #"Descriptive Parameter Statistics", 
            "Tabulated NM Diagnostic",
            "Demographic tables (categorical)",
            "Demographic tables (continuous)",
            "Goodness of fit",
            "Table from disk",
            "Figure from disk",
            "Listing from disk (table or figure as png)",
            "Listing from disk (text file)",
            "Subject exclusions listing",
            "Observations exclusions listing",
            "Summary of subject exclusions",
            "Summary of observation exclusions",
            "Variable distribution (multipanel)",
            "Bar charts (multipanel)"
            #, "Descriptive Listing"
    ),
    value=rep(0,23),
    # value=c(Defaults$ConcvTimeNum,
    #         Defaults$ConcvTimeMultNum,
    #         Defaults$ConcvTimeGroupNum,
    #         Defaults$demogTabNum,
    #         #Defaults$demog1TabNum,
    #         Defaults$OBSvPREDNum,
    #         Defaults$paramDistNum,
    #         Defaults$covCatNum,
    #         Defaults$covConNum,
    #         Defaults$corPairsNum,
    #         Defaults$QQplotNum,
    #         Defaults$DescParamStatNum,
    #         Defaults$NMTabNum,
    #         Defaults$demogTabContNum,
    #         Defaults$demogTabCatNum,
    #         Defaults$GOFNum,
    #         Defaults$inputTableNum,
    #         Defaults$inputFigureNum,
    #         Defaults$inputListingNum,
    #         Defaults$inputListing_textNum,
    #         Defaults$subjectExclusionsTabNum,
    #         Defaults$observationsExclusionsTabNum
    #         #, Defaults$DescListNum
    # ),
    tabType=c("PKInputFigures",
              "Listings",
              "PKInputFigures",
              #"InputTables", 
              #"InputTables", 
              "ModelFigures",
              "ModelFigures",
              "ModelFigures",
              "ModelFigures",
              "ModelFigures",
              "ModelFigures",
              "Tables",
              #"AnalysisTables",
              "Tables",
              "Tables",
              "ModelFigures",
              "Tables",
              "ModelFigures",
              "Listings",
              "Listings",
              "Listings",
              "Listings",
              "Tables",
              "Tables",
              "ModelFigures",
              "ModelFigures"
              #, "Listings"
    ),
    sidebarType=c("Figures",
                  "Listings",
                  "Figures",
                  #"Tables",
                  #"Tables",
                  "Figures",
                  "Figures",
                  "Figures",
                  "Figures",
                  "Figures",
                  "Figures",
                  "Tables",
                  #"Tables",
                  "Tables",
                  "Tables",
                  "Figures",
                  "Tables",
                  "Figures",
                  "Listings",
                  "Listings",
                  "Listings",
                  "Listings",
                  "Tables",
                  "Tables",
                  "Figures",
                  "Figures"
                  #,"Listings"
    )
)



save(tabList,file=file.path(gitDir,"GUI","data","tabList.rda")) # Expects to run from top of repo
